
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
    ports:
      - '8081:5000'
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    ports:
      - '8082:5000'
  nginx:
    build: ./nginx
    ports:
    - '8080:8080'
    depends_on:
    - web1
    - web2


